"""Closed TASK-168 blocker vocabulary."""

from __future__ import annotations

import enum


class BlockerCode(enum.StrEnum):
    INVALID_REQUEST_TYPE = "INVALID_REQUEST_TYPE"
    INVALID_REQUEST_SCHEMA = "INVALID_REQUEST_SCHEMA"
    SOURCE_DEFINITION_MISMATCH = "SOURCE_DEFINITION_MISMATCH"
    UNSUPPORTED_RAW_VALUE = "UNSUPPORTED_RAW_VALUE"
    RAW_UNICODE_ENCODING_FAILURE = "RAW_UNICODE_ENCODING_FAILURE"
    RAW_DEPTH_LIMIT_EXCEEDED = "RAW_DEPTH_LIMIT_EXCEEDED"
    RAW_NODE_LIMIT_EXCEEDED = "RAW_NODE_LIMIT_EXCEEDED"
    RAW_SCALAR_BYTE_LIMIT_EXCEEDED = "RAW_SCALAR_BYTE_LIMIT_EXCEEDED"
    CONFIGURATION_AUTHORITY_INVALID = "CONFIGURATION_AUTHORITY_INVALID"
    REQUIREMENT_AUTHORITY_INVALID = "REQUIREMENT_AUTHORITY_INVALID"
    DISCRETE_AUTHORITY_INVALID = "DISCRETE_AUTHORITY_INVALID"
    DISCRETE_AUTHORITY_UNAPPROVED = "DISCRETE_AUTHORITY_UNAPPROVED"
    DISCRETE_AUTHORITY_EVIDENCE_MISSING = "DISCRETE_AUTHORITY_EVIDENCE_MISSING"
    DISCRETE_AUTHORITY_HASH_MISMATCH = "DISCRETE_AUTHORITY_HASH_MISMATCH"
    DUPLICATE_DISCRETE_MEMBER = "DUPLICATE_DISCRETE_MEMBER"
    UNKNOWN_DIMENSION_ROLE = "UNKNOWN_DIMENSION_ROLE"
    SHELL_CATALOG_INVALID = "SHELL_CATALOG_INVALID"
    SHELL_CATALOG_RECORD_INVALID = "SHELL_CATALOG_RECORD_INVALID"
    RESOURCE_BOUND_EXCEEDED = "RESOURCE_BOUND_EXCEEDED"
    CANDIDATE_GEOMETRY_INVALID = "CANDIDATE_GEOMETRY_INVALID"
    EVALUATION_AUTHORITY_REQUIRED = "EVALUATION_AUTHORITY_REQUIRED"
    TASK021_REPLAY_FAILED = "TASK021_REPLAY_FAILED"
    TASK022_REPLAY_FAILED = "TASK022_REPLAY_FAILED"
    TASK024_REPLAY_FAILED = "TASK024_REPLAY_FAILED"
    TUBE_SIDE_REPLAY_FAILED = "TUBE_SIDE_REPLAY_FAILED"
    OVERALL_RESISTANCE_REPLAY_FAILED = "OVERALL_RESISTANCE_REPLAY_FAILED"
    UA_REPLAY_FAILED = "UA_REPLAY_FAILED"
    TASK162_REPLAY_FAILED = "TASK162_REPLAY_FAILED"
    TASK166_REPLAY_FAILED = "TASK166_REPLAY_FAILED"
    TASK167_REPLAY_FAILED = "TASK167_REPLAY_FAILED"
    UPSTREAM_CASE_BINDING_MISMATCH = "UPSTREAM_CASE_BINDING_MISMATCH"
    CONSTRAINT_AUTHORITY_INVALID = "CONSTRAINT_AUTHORITY_INVALID"
    HARD_CONSTRAINT_UNSATISFIED = "HARD_CONSTRAINT_UNSATISFIED"
    CANDIDATE_STAGE_FAILED = "CANDIDATE_STAGE_FAILED"
    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    IDENTITY_REPLAY_FAILED = "IDENTITY_REPLAY_FAILED"
    INTERNAL_INVARIANT_VIOLATION = "INTERNAL_INVARIANT_VIOLATION"


class FailureStage(enum.StrEnum):
    RAW_BOUNDARY = "RAW_BOUNDARY"
    TYPED_VALIDATION = "TYPED_VALIDATION"
    CANDIDATE_AUTHORITY = "CANDIDATE_AUTHORITY"
    CONFIGURATION = "CONFIGURATION"
    TUBE_LAYOUT = "TUBE_LAYOUT"
    SHELL_BUNDLE_GEOMETRY = "SHELL_BUNDLE_GEOMETRY"
    BAFFLE_GEOMETRY = "BAFFLE_GEOMETRY"
    TUBE_SIDE = "TUBE_SIDE"
    SHELL_SIDE_BELL = "SHELL_SIDE_BELL"
    OVERALL_RESISTANCE = "OVERALL_RESISTANCE"
    UA = "UA"
    THERMAL_CLOSURE = "THERMAL_CLOSURE"
    TUBE_DP = "TUBE_DP"
    SHELL_DP = "SHELL_DP"
    ENGINEERING_SCREENING = "ENGINEERING_SCREENING"
    CONSTRAINT_EVALUATION = "CONSTRAINT_EVALUATION"
    PROVENANCE = "PROVENANCE"
    IDENTITY = "IDENTITY"


BLOCKER_CODE_VOCABULARY = tuple(item.value for item in BlockerCode)
FAILURE_STAGE_VOCABULARY = tuple(item.value for item in FailureStage)


__all__ = [
    "BLOCKER_CODE_VOCABULARY",
    "FAILURE_STAGE_VOCABULARY",
    "BlockerCode",
    "FailureStage",
]
