"""Closed structural failures. No convergence/engineering PASS vocabulary."""

from enum import StrEnum


class Code(StrEnum):
    RAW_BOUNDARY_INVALID = "RAW_BOUNDARY_INVALID"
    TOPOLOGY_AUTHORITY_INCOMPLETE = "TOPOLOGY_AUTHORITY_INCOMPLETE"
    UPSTREAM_IDENTITY_MISMATCH = "UPSTREAM_IDENTITY_MISMATCH"
    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    UNSUPPORTED_TOPOLOGY = "UNSUPPORTED_TOPOLOGY"
    INVALID_CONNECTIVITY = "INVALID_CONNECTIVITY"
    INVALID_PHYSICAL_MAPPING = "INVALID_PHYSICAL_MAPPING"
    INVALID_MESH_MAPPING = "INVALID_MESH_MAPPING"
    DUPLICATE_PHYSICAL_EVENT = "DUPLICATE_PHYSICAL_EVENT"
    INVALID_AREA_OWNERSHIP = "INVALID_AREA_OWNERSHIP"
    UNLOCATED_STATE = "UNLOCATED_STATE"
    CONSERVATION_INPUT_INCOMPLETE = "CONSERVATION_INPUT_INCOMPLETE"


class Failure(Exception):
    def __init__(self, code: Code, field: str) -> None:
        self.code = code
        self.field = field
        super().__init__(code.value)
