"""Failure taxonomy for the TASK162 boundary and numerical service."""

from __future__ import annotations

from enum import StrEnum

from .models import Task162Blocker, Task162FailureStage


class Task162FailureCode(StrEnum):
    INVALID_REQUEST_TYPE = "INVALID_REQUEST_TYPE"
    INVALID_REQUEST_SCHEMA = "INVALID_REQUEST_SCHEMA"
    UNSUPPORTED_TASK162_VERSION = "UNSUPPORTED_TASK162_VERSION"
    SOURCE_DEFINITION_ID_MISMATCH = "SOURCE_DEFINITION_ID_MISMATCH"
    UNSUPPORTED_RAW_VALUE = "UNSUPPORTED_RAW_VALUE"
    INVALID_TASK160_RESULT = "INVALID_TASK160_RESULT"
    TASK160_IDENTITY_REPLAY_FAILED = "TASK160_IDENTITY_REPLAY_FAILED"
    TASK160_NOT_APPLICABLE = "TASK160_NOT_APPLICABLE"
    TASK160_NOT_COMPLETE = "TASK160_NOT_COMPLETE"
    INVALID_TASK161_RESULT = "INVALID_TASK161_RESULT"
    TASK161_IDENTITY_REPLAY_FAILED = "TASK161_IDENTITY_REPLAY_FAILED"
    TASK161_NOT_APPLICABLE = "TASK161_NOT_APPLICABLE"
    TASK161_NOT_COMPLETE = "TASK161_NOT_COMPLETE"
    TASK161_TASK160_IDENTITY_MISMATCH = "TASK161_TASK160_IDENTITY_MISMATCH"
    INVALID_TASK038_RESULT = "INVALID_TASK038_RESULT"
    TASK038_IDENTITY_REPLAY_FAILED = "TASK038_IDENTITY_REPLAY_FAILED"
    TASK038_NOT_APPLICABLE = "TASK038_NOT_APPLICABLE"
    TASK038_NOT_COMPLETE = "TASK038_NOT_COMPLETE"
    CROSS_PRODUCER_BINDING_INVALID = "CROSS_PRODUCER_BINDING_INVALID"
    CROSS_PRODUCER_CASE_MISMATCH = "CROSS_PRODUCER_CASE_MISMATCH"
    TUBE_SIDE_SERVICE_BINDING_MISMATCH = "TUBE_SIDE_SERVICE_BINDING_MISMATCH"
    SHELL_SIDE_SERVICE_BINDING_MISMATCH = "SHELL_SIDE_SERVICE_BINDING_MISMATCH"
    CASE_AUTHORITY_INVALID = "CASE_AUTHORITY_INVALID"
    CASE_BINDING_INCOMPLETE = "CASE_BINDING_INCOMPLETE"
    CASE_BINDING_VALUE_MISMATCH = "CASE_BINDING_VALUE_MISMATCH"
    UNSUPPORTED_BAFFLE_COUNT = "UNSUPPORTED_BAFFLE_COUNT"
    CATALOG_AUTHORITY_INVALID = "CATALOG_AUTHORITY_INVALID"
    INVALID_UA = "INVALID_UA"
    INVALID_C_MIN = "INVALID_C_MIN"
    INVALID_R_SOURCE = "INVALID_R_SOURCE"
    INVALID_NTU = "INVALID_NTU"
    INVALID_INLET_TEMPERATURE_ORDER = "INVALID_INLET_TEMPERATURE_ORDER"
    PERFORMANCE_RELATION_DOMAIN_ERROR = "PERFORMANCE_RELATION_DOMAIN_ERROR"
    PERFORMANCE_RELATION_SINGULARITY = "PERFORMANCE_RELATION_SINGULARITY"
    PERFORMANCE_RELATION_NONFINITE = "PERFORMANCE_RELATION_NONFINITE"
    INVALID_P_SOURCE = "INVALID_P_SOURCE"
    INVALID_EFFECTIVENESS = "INVALID_EFFECTIVENESS"
    INVALID_HEAT_DUTY = "INVALID_HEAT_DUTY"
    ENERGY_BALANCE_CLOSURE_FAILED = "ENERGY_BALANCE_CLOSURE_FAILED"
    TERMINAL_TEMPERATURE_CLOSURE_FAILED = "TERMINAL_TEMPERATURE_CLOSURE_FAILED"
    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    IDENTITY_REPLAY_FAILED = "IDENTITY_REPLAY_FAILED"
    INTERNAL_INVARIANT_VIOLATION = "INTERNAL_INVARIANT_VIOLATION"


def blocker(
    code: Task162FailureCode,
    stage: Task162FailureStage,
    evidence_refs: tuple[str, ...] = (),
) -> Task162Blocker:
    """Create a stable blocker without free-form exception text."""

    return Task162Blocker(code=code.value, stage=stage, evidence_refs=evidence_refs)


def normalized_blockers(
    values: tuple[Task162Blocker, ...] | list[Task162Blocker],
) -> tuple[Task162Blocker, ...]:
    """Deduplicate and sort blockers by their semantic identity."""

    unique = {(item.code, item.stage.value, item.evidence_refs): item for item in values}
    return tuple(
        unique[key] for key in sorted(unique, key=lambda item: (item[0], item[1], tuple(item[2])))
    )
