"""R7 static identity oracle for TASK037.

These literals are source-controlled expected values.  They are intentionally
not generated by production code at import time.
"""

from __future__ import annotations

from decimal import Decimal

R7_FIXTURE_ID = "R7-FIXTURE-001"
REQUEST_HASH_A = "1" * 64
REQUEST_HASH_B = "2" * 64
TASK021_LAYOUT_HASH = "1" * 64
TASK025_RESULT_HASH = "2" * 64
TASK025_HYDRAULIC_AUTHORITY_HASH = "3" * 64
TUBE_GEOMETRY_SNAPSHOT_HASH = "4" * 64
HEAT_TRANSFER_LENGTH_HASH = "5" * 64
WALL_MATERIAL_AUTHORITY_HASH = "6" * 64
WALL_CONDUCTIVITY_AUTHORITY_HASH = "7" * 64
INSIDE_FOULING_AUTHORITY_HASH = "8" * 64
OUTSIDE_FOULING_AUTHORITY_HASH = "9" * 64
POLICY_HASH = "9d813406416e734d7f4ece78adcdb9e05155c5f43a3e5cbe18b8f73917ae85e9"

SURFACE_HASH = "19690b6fd6694284daa1daa7a001f261555dcd08c6d21ec99940e35ee97612bc"
WALL_HASH = "3086bcae0faf0a2b92b626740fa0e913200ddbe3615aa7aaad33dec60f41b29c"
PROVENANCE_HASH_A = "b9d17f8547da700e09e34650ea643931d31b8ee8a18bb764c98f5210552c1760"
PROVENANCE_HASH_B = "5d841a64b2215a9d8c89424431f29516b4c9c6e781064f1c35a1e796f5671fb4"
RESULT_HASH_A = "09c5ecbbfe86f0ae403009f1ed45298250432b55d90c68a43e7c98b3f66595c9"
RESULT_HASH_B = "c8c6b8ac1e31e663b7128edb7755246ffdc53cbe704a06df7149d617cf282d3f"
RESULT_ID_A = "537d256e-ac25-51da-b74c-698f2e36df05"
RESULT_ID_B = "7649d8a5-8f20-5abb-9144-3f01bf2bd2c8"

SURFACE = {
    "task021_layout_hash": TASK021_LAYOUT_HASH,
    "task025_result_hash": TASK025_RESULT_HASH,
    "task025_hydraulic_authority_hash": TASK025_HYDRAULIC_AUTHORITY_HASH,
    "tube_geometry_snapshot_hash": TUBE_GEOMETRY_SNAPSHOT_HASH,
    "tube_inner_diameter_m": Decimal("0.020"),
    "tube_outer_diameter_m": Decimal("0.024"),
    "tube_side_film_reference_surface": "INNER_TUBE_SURFACE",
    "overall_u_reference_surface": "OUTER_TUBE_SURFACE",
    "outer_to_inner_area_ratio": Decimal("1.200000000000000"),
    "engineering_source_id": "T037-S01-DOE-HDBK-1012-2-92",
    "engineering_source_locations": (
        "T037-S01-L01|HT-02_Page_12|PDF_ZERO_BASED_PAGE=33|EQUATION=2-7",
        "T037-S01-L04|HT-02_Page_22|PDF_ZERO_BASED_PAGE=43|EQUATION=2-10",
    ),
}

WALL = {
    "surface_transform_authority_hash": SURFACE_HASH,
    "task025_result_hash": TASK025_RESULT_HASH,
    "task025_hydraulic_authority_hash": TASK025_HYDRAULIC_AUTHORITY_HASH,
    "task025_internal_heat_transfer_surface_area_m2": Decimal("0.0314159265"),
    "task025_area_quantum_m2": Decimal("1E-10"),
    "task025_area_rounding_mode": "ROUND_HALF_EVEN",
    "producer_area_precision_policy_id": "task037.task025-public-area-authority.accept-positive-v1",
    "producer_area_precision_policy_hash": POLICY_HASH,
    "producer_precision_limitation_disclosed": True,
    "producer_precision_threshold_defined": False,
    "wall_bundle_numerical_basis": "TASK025_PUBLIC_INNER_AREA_PROJECTION_V1",
    "wall_material_authority_hash": WALL_MATERIAL_AUTHORITY_HASH,
    "wall_conductivity_authority_hash": WALL_CONDUCTIVITY_AUTHORITY_HASH,
    "wall_bundle_conduction_resistance_k_w": Decimal("0.003627172128641"),
    "wall_resistance_outer_surface_m2_k_w": Decimal("0.000136741167595"),
    "engineering_source_id": "T037-S01-DOE-HDBK-1012-2-92",
    "engineering_source_location": "T037-S01-L02|HT-02_Page_13|PDF_ZERO_BASED_PAGE=34|EQUATION=2-8",
    "source_formula_identity": "EXACT_CYLINDRICAL_WALL_RESISTANCE",
    "thin_wall_approximation_used": False,
}

INSIDE_FOULING = {
    "authority_id": "R7-FIX-IN-FOULING",
    "reference_surface": "INNER_TUBE_SURFACE",
    "resistance_value_m2_k_w": Decimal("0.000100000000000"),
    "resistance_units": "m2_K_per_W",
    "fluid_service_id": "FIXTURE_INNER_SERVICE",
    "source_id": "FIXTURE-APPROVED-FOULING-AUTHORITY-V1",
    "source_version": "R7",
    "source_location": "R7_STATIC_FIXTURE_DECLARATION",
    "permission_status": "ADMITTED",
    "approval_status": "APPROVED",
    "applicability": "SINGLE_PHASE_FIXTURE_SERVICE",
    "authority_hash": INSIDE_FOULING_AUTHORITY_HASH,
}
OUTSIDE_FOULING = {
    "authority_id": "R7-FIX-OUT-FOULING",
    "reference_surface": "OUTER_TUBE_SURFACE",
    "resistance_value_m2_k_w": Decimal("0.000200000000000"),
    "resistance_units": "m2_K_per_W",
    "fluid_service_id": "FIXTURE_OUTER_SERVICE",
    "source_id": "FIXTURE-APPROVED-FOULING-AUTHORITY-V1",
    "source_version": "R7",
    "source_location": "R7_STATIC_FIXTURE_DECLARATION",
    "permission_status": "ADMITTED",
    "approval_status": "APPROVED",
    "applicability": "SINGLE_PHASE_FIXTURE_SERVICE",
    "authority_hash": OUTSIDE_FOULING_AUTHORITY_HASH,
}

FOULING_LEDGER = (
    "inside=PASS:INNER_TUBE_SURFACE:0.000100000000000",
    "outside=PASS:OUTER_TUBE_SURFACE:0.000200000000000",
)
APPLICABILITY_LEDGER = (
    "A01_TASK021_VALID=PASS",
    "A02_TASK025_VALID=PASS",
    "A03_TASK021_TASK025_IDENTITY_COMPATIBLE=PASS",
    "A04_CYLINDRICAL_GEOMETRY_VALID=PASS",
    "A05_TUBE_SIDE_FILM_SURFACE_AUTHORITY_ESTABLISHED=PASS",
    "A06_SURFACE_TRANSFORM_APPLICABLE=PASS",
    "A07_WALL_MATERIAL_AUTHORITY_ADMISSIBLE=PASS",
    "A08_WALL_CONDUCTIVITY_AUTHORITY_ADMISSIBLE=PASS",
    "A09_INSIDE_FOULING_AUTHORITY_ADMISSIBLE=PASS",
    "A10_OUTSIDE_FOULING_AUTHORITY_ADMISSIBLE=PASS",
)
COMPLETENESS_LEDGER = (
    "C01_SURFACE_BASIS_AUTHORITY_COMPLETE=PASS",
    "C02_WALL_RESISTANCE_AUTHORITY_COMPLETE=PASS",
    "C03_INSIDE_FOULING_AUTHORITY_COMPLETE=PASS",
    "C04_OUTSIDE_FOULING_AUTHORITY_COMPLETE=PASS",
    "C05_FOULING_AUTHORITY_LEDGER_COMPLETE=PASS",
    "C06_TASK038_FORWARD_CONSUMER_CONTRACT_COMPLETE=PASS",
)
DEFERRED = (
    "OVERALL_U",
    "UA",
    "LMTD",
    "HEAT_DUTY",
    "OUTLET_TEMPERATURES",
    "FULL_EXCHANGER_THERMAL_RATING",
)


def provenance_fixture(request_hash: str, terminal_hash: str) -> dict[str, object]:
    return {
        "task_id": "TASK037",
        "source_definition_issue": 208,
        "source_definition_revision": "R3_FROZEN",
        "source_definition_review_audit_comment": 5461369330,
        "design_issue": 209,
        "design_revision": "R7_FINAL_FROZEN",
        "implementation_software_version": "task037.overall-heat-transfer-resistance.impl-v1",
        "request_hash": request_hash,
        "task021_layout_hash": TASK021_LAYOUT_HASH,
        "task025_result_hash": TASK025_RESULT_HASH,
        "task025_hydraulic_authority_hash": TASK025_HYDRAULIC_AUTHORITY_HASH,
        "tube_geometry_snapshot_hash": TUBE_GEOMETRY_SNAPSHOT_HASH,
        "heat_transfer_length_hash": HEAT_TRANSFER_LENGTH_HASH,
        "task025_internal_heat_transfer_surface_area_m2": Decimal("0.0314159265"),
        "task025_area_quantum_m2": Decimal("1E-10"),
        "task025_area_rounding_mode": "ROUND_HALF_EVEN",
        "producer_area_precision_policy_id": (
            "task037.task025-public-area-authority.accept-positive-v1"
        ),
        "producer_area_precision_policy_hash": POLICY_HASH,
        "producer_precision_limitation_disclosed": True,
        "producer_precision_threshold_defined": False,
        "wall_material_authority_hash": WALL_MATERIAL_AUTHORITY_HASH,
        "wall_conductivity_authority_hash": WALL_CONDUCTIVITY_AUTHORITY_HASH,
        "inside_fouling_authority_hash": INSIDE_FOULING_AUTHORITY_HASH,
        "outside_fouling_authority_hash": OUTSIDE_FOULING_AUTHORITY_HASH,
        "surface_transform_authority_hash": SURFACE_HASH,
        "wall_resistance_authority_hash": WALL_HASH,
        "source_identity_hashes": (
            POLICY_HASH,
            WALL_MATERIAL_AUTHORITY_HASH,
            WALL_CONDUCTIVITY_AUTHORITY_HASH,
            INSIDE_FOULING_AUTHORITY_HASH,
            OUTSIDE_FOULING_AUTHORITY_HASH,
        ),
        "producer_edges": (
            "TASK021->TASK025",
            "TASK025->TASK037",
            "TASK037.surface->TASK037.wall",
            "TASK037.wall->TASK037.provenance",
            "TASK037.provenance->TASK037.result",
        ),
        "evidence_refs": ("ISSUE_208#5461369330", "ISSUE_209#R7_STATIC_FIXTURE_001"),
        "deferred_capabilities": DEFERRED,
        "provenance_hash": terminal_hash,
    }


def result_fixture(request_hash: str, provenance: dict[str, object]) -> dict[str, object]:
    return {
        "request_hash": request_hash,
        "task021_identity": {
            "identity_type": "task021.tube-layout.v1",
            "identity_id": "R7-FIX-T021-001",
            "identity_hash": TASK021_LAYOUT_HASH,
        },
        "task025_identity": {
            "identity_type": "task025.tube-side.v1",
            "identity_id": "R7-FIX-T025-001",
            "identity_hash": TASK025_RESULT_HASH,
        },
        "task025_hydraulic_authority_hash": TASK025_HYDRAULIC_AUTHORITY_HASH,
        "tube_geometry_snapshot_hash": TUBE_GEOMETRY_SNAPSHOT_HASH,
        "heat_transfer_length_hash": HEAT_TRANSFER_LENGTH_HASH,
        "tube_side_film_reference_surface": "INNER_TUBE_SURFACE",
        "overall_u_reference_surface": "OUTER_TUBE_SURFACE",
        "outer_to_inner_area_ratio": Decimal("1.200000000000000"),
        "surface_transform_authority_hash": SURFACE_HASH,
        "wall_material_authority_hash": WALL_MATERIAL_AUTHORITY_HASH,
        "wall_conductivity_authority_hash": WALL_CONDUCTIVITY_AUTHORITY_HASH,
        "wall_bundle_conduction_resistance_k_w": Decimal("0.003627172128641"),
        "wall_resistance_outer_surface_m2_k_w": Decimal("0.000136741167595"),
        "inside_fouling_authority": INSIDE_FOULING,
        "outside_fouling_authority": OUTSIDE_FOULING,
        "fouling_authority_ledger": FOULING_LEDGER,
        "applicability_ledger": APPLICABILITY_LEDGER,
        "completeness_ledger": COMPLETENESS_LEDGER,
        "warnings": (),
        "blockers": (),
        "deferred_capabilities": DEFERRED,
        "provenance": provenance,
    }
