"""Public TASK-038 overall heat-transfer coefficient and UA boundary."""

from .canonical import (
    CanonicalizationError,
    cross_producer_compatibility_hash,
    engineering_source_identity_hash,
    frame_record,
    frame_tuple,
    frame_value,
    outer_area_projection_hash,
    producer_envelope_hash,
    provenance_hash,
    request_hash,
    resistance_composition_hash,
    result_hash,
    result_id,
    service_binding_hash,
    sha256_hex,
    success_result_hash,
    thermal_resistance_ledger_row_hash,
    ua_composition_hash,
)
from .models import (
    BlockerEntry,
    EngineeringSourceIdentity,
    LedgerRow,
    ProducerIdentityEnvelope,
    Task038BlockedResult,
    Task038Provenance,
    Task038RawBlockedResult,
    Task038RawBoundaryBlockedResult,
    Task038Request,
    Task038Result,
    Task038SuccessResult,
    Task038TypedBlockedResult,
    Task038ValidationResult,
    ThermalResistanceLedgerRow,
    TubeSideServiceBindingAuthority,
    WarningEntry,
)
from .producer_replay import (
    producer_identity_envelope,
    replay_result,
    replay_task025,
    replay_task026,
    replay_task035,
    replay_task037,
    task026_raw_replay_hash,
)
from .raw_projection import FrozenRawProjection
from .schema import *  # noqa: F403
from .validation import (
    build_raw_overall_u_ua_request,
    compute_overall_heat_transfer_coefficient_and_ua,
    evaluate_task038,
    verify_task038_success_identity,
)

__all__ = [
    "BlockerEntry",
    "CanonicalizationError",
    "EngineeringSourceIdentity",
    "FrozenRawProjection",
    "LedgerRow",
    "ProducerIdentityEnvelope",
    "Task038BlockedResult",
    "Task038Provenance",
    "Task038RawBoundaryBlockedResult",
    "Task038RawBlockedResult",
    "Task038Request",
    "Task038Result",
    "Task038SuccessResult",
    "Task038TypedBlockedResult",
    "Task038ValidationResult",
    "ThermalResistanceLedgerRow",
    "TubeSideServiceBindingAuthority",
    "WarningEntry",
    "build_raw_overall_u_ua_request",
    "compute_overall_heat_transfer_coefficient_and_ua",
    "cross_producer_compatibility_hash",
    "engineering_source_identity_hash",
    "evaluate_task038",
    "frame_record",
    "frame_tuple",
    "frame_value",
    "outer_area_projection_hash",
    "producer_envelope_hash",
    "producer_identity_envelope",
    "provenance_hash",
    "replay_result",
    "replay_task025",
    "replay_task026",
    "replay_task035",
    "replay_task037",
    "request_hash",
    "resistance_composition_hash",
    "result_hash",
    "result_id",
    "service_binding_hash",
    "sha256_hex",
    "success_result_hash",
    "task026_raw_replay_hash",
    "thermal_resistance_ledger_row_hash",
    "ua_composition_hash",
    "verify_task038_success_identity",
]
