"""Closed TASK-033 blocker registry and stable ordering."""

from __future__ import annotations

from collections.abc import Iterable
from enum import StrEnum

from .models import BlockerEntry


class BlockerCode(StrEnum):
    SSHT_SCHEMA_VERSION_UNSUPPORTED = "SSHT_SCHEMA_VERSION_UNSUPPORTED"
    SSHT_PROFILE_ID_UNSUPPORTED = "SSHT_PROFILE_ID_UNSUPPORTED"
    SSHT_RAW_TYPE_INVALID = "SSHT_RAW_TYPE_INVALID"
    SSHT_UNKNOWN_FIELD = "SSHT_UNKNOWN_FIELD"
    SSHT_EVIDENCE_REFS_INVALID = "SSHT_EVIDENCE_REFS_INVALID"
    SSHT_TASK032_FLOW_STATE_MISSING = "SSHT_TASK032_FLOW_STATE_MISSING"
    SSHT_TASK032_FLOW_STATE_INVALID = "SSHT_TASK032_FLOW_STATE_INVALID"
    SSHT_TASK032_REQUEST_EVIDENCE_MISSING = "SSHT_TASK032_REQUEST_EVIDENCE_MISSING"
    SSHT_TASK032_REQUEST_EVIDENCE_INVALID = "SSHT_TASK032_REQUEST_EVIDENCE_INVALID"
    SSHT_TASK032_REQUEST_HASH_MISMATCH = "SSHT_TASK032_REQUEST_HASH_MISMATCH"
    SSHT_TASK032_RESULT_HASH_MISMATCH = "SSHT_TASK032_RESULT_HASH_MISMATCH"
    SSHT_TASK032_RESULT_ID_MISMATCH = "SSHT_TASK032_RESULT_ID_MISMATCH"
    SSHT_TASK031_GEOMETRY_REPLAY_MISMATCH = "SSHT_TASK031_GEOMETRY_REPLAY_MISMATCH"
    SSHT_PROPERTY_SNAPSHOT_HASH_MISMATCH = "SSHT_PROPERTY_SNAPSHOT_HASH_MISMATCH"
    SSHT_MASS_FLOW_AUTHORITY_HASH_MISMATCH = "SSHT_MASS_FLOW_AUTHORITY_HASH_MISMATCH"
    SSHT_SAME_CASE_BINDING_MISMATCH = "SSHT_SAME_CASE_BINDING_MISMATCH"
    SSHT_PHASE_UNSUPPORTED = "SSHT_PHASE_UNSUPPORTED"
    SSHT_RHEOLOGY_MODEL_UNSUPPORTED = "SSHT_RHEOLOGY_MODEL_UNSUPPORTED"
    SSHT_PROPERTY_STATE_ROLE_UNSUPPORTED = "SSHT_PROPERTY_STATE_ROLE_UNSUPPORTED"
    SSHT_FLOW_REGION_UNSUPPORTED = "SSHT_FLOW_REGION_UNSUPPORTED"
    SSHT_REYNOLDS_OUTSIDE_CORRELATION_DOMAIN = "SSHT_REYNOLDS_OUTSIDE_CORRELATION_DOMAIN"
    SSHT_CORRELATION_AUTHORITY_IDENTITY_MISMATCH = "SSHT_CORRELATION_AUTHORITY_IDENTITY_MISMATCH"
    SSHT_FORMULA_INPUT_DOMAIN_VIOLATION = "SSHT_FORMULA_INPUT_DOMAIN_VIOLATION"
    SSHT_FRACTIONAL_POWER_CALCULATION_FAILED = "SSHT_FRACTIONAL_POWER_CALCULATION_FAILED"
    SSHT_FORMULA_CALCULATION_FAILED = "SSHT_FORMULA_CALCULATION_FAILED"
    SSHT_PUBLIC_HTC_QUANTIZATION_COLLISION = "SSHT_PUBLIC_HTC_QUANTIZATION_COLLISION"
    SSHT_CANONICALIZATION_FAILED = "SSHT_CANONICALIZATION_FAILED"
    SSHT_RESULT_IDENTITY_FINALIZATION_FAILED = "SSHT_RESULT_IDENTITY_FINALIZATION_FAILED"
    SSHT_PARTIAL_RESULT_FORBIDDEN = "SSHT_PARTIAL_RESULT_FORBIDDEN"


TASK033_BLOCKER_REGISTRY: tuple[str, ...] = tuple(code.value for code in BlockerCode)
TASK033_BLOCKER_CODE_COUNT = 29
TASK033_BLOCKER_EARLIEST_STAGE: dict[str, str] = {
    BlockerCode.SSHT_SCHEMA_VERSION_UNSUPPORTED: "S01",
    BlockerCode.SSHT_PROFILE_ID_UNSUPPORTED: "S01",
    BlockerCode.SSHT_RAW_TYPE_INVALID: "S00",
    BlockerCode.SSHT_UNKNOWN_FIELD: "S01",
    BlockerCode.SSHT_EVIDENCE_REFS_INVALID: "S01",
    BlockerCode.SSHT_TASK032_FLOW_STATE_MISSING: "S02",
    BlockerCode.SSHT_TASK032_FLOW_STATE_INVALID: "S02",
    BlockerCode.SSHT_TASK032_REQUEST_EVIDENCE_MISSING: "S02",
    BlockerCode.SSHT_TASK032_REQUEST_EVIDENCE_INVALID: "S02",
    BlockerCode.SSHT_TASK032_REQUEST_HASH_MISMATCH: "S04",
    BlockerCode.SSHT_TASK032_RESULT_HASH_MISMATCH: "S03",
    BlockerCode.SSHT_TASK032_RESULT_ID_MISMATCH: "S03",
    BlockerCode.SSHT_TASK031_GEOMETRY_REPLAY_MISMATCH: "S05",
    BlockerCode.SSHT_PROPERTY_SNAPSHOT_HASH_MISMATCH: "S06",
    BlockerCode.SSHT_MASS_FLOW_AUTHORITY_HASH_MISMATCH: "S07",
    BlockerCode.SSHT_SAME_CASE_BINDING_MISMATCH: "S08",
    BlockerCode.SSHT_PHASE_UNSUPPORTED: "S09",
    BlockerCode.SSHT_RHEOLOGY_MODEL_UNSUPPORTED: "S09",
    BlockerCode.SSHT_PROPERTY_STATE_ROLE_UNSUPPORTED: "S09",
    BlockerCode.SSHT_FLOW_REGION_UNSUPPORTED: "S09",
    BlockerCode.SSHT_REYNOLDS_OUTSIDE_CORRELATION_DOMAIN: "S09",
    BlockerCode.SSHT_CORRELATION_AUTHORITY_IDENTITY_MISMATCH: "S09",
    BlockerCode.SSHT_FORMULA_INPUT_DOMAIN_VIOLATION: "S10",
    BlockerCode.SSHT_FRACTIONAL_POWER_CALCULATION_FAILED: "S11",
    BlockerCode.SSHT_FORMULA_CALCULATION_FAILED: "S11",
    BlockerCode.SSHT_PUBLIC_HTC_QUANTIZATION_COLLISION: "S12",
    BlockerCode.SSHT_CANONICALIZATION_FAILED: "S13",
    BlockerCode.SSHT_RESULT_IDENTITY_FINALIZATION_FAILED: "S14",
    BlockerCode.SSHT_PARTIAL_RESULT_FORBIDDEN: "S14",
}


def make_blocker(
    code: BlockerCode | str,
    *,
    stage: str | None = None,
    field_path: str | None = None,
    details: Iterable[tuple[str, str]] = (),
) -> BlockerEntry:
    token = code.value if isinstance(code, BlockerCode) else code
    if token not in TASK033_BLOCKER_REGISTRY:
        raise ValueError(f"unknown TASK033 blocker token: {token!r}")
    return BlockerEntry(
        code=token,
        stage=stage or TASK033_BLOCKER_EARLIEST_STAGE[token],
        field_path=field_path,
        message_key=token.lower(),
        details=tuple(sorted((str(k), str(v)) for k, v in details)),
    )


def sort_blockers(entries: Iterable[BlockerEntry]) -> tuple[BlockerEntry, ...]:
    return tuple(
        sorted(
            entries,
            key=lambda entry: (
                int(entry.stage[1:]) if entry.stage[1:].isdigit() else 99,
                entry.code,
                entry.field_path or "",
                entry.message_key,
                entry.details,
            ),
        )
    )


__all__ = [
    "BlockerCode",
    "TASK033_BLOCKER_CODE_COUNT",
    "TASK033_BLOCKER_EARLIEST_STAGE",
    "TASK033_BLOCKER_REGISTRY",
    "make_blocker",
    "sort_blockers",
]
