"""Frozen source authority for the preferred TASK-033 correlation."""

from __future__ import annotations

from hexagent.exchangers.shell_tube.tube_layout.canonical import sha256_hex

ENGINEERING_AUTHORITY_ID = "TASK033_KERN_KHARAJI_2021_EQ58_NO_WALL_CORRECTION_V1"
ENGINEERING_SOURCE_AUTHORITY_RECORD_ID = "5387111841"
SOURCE_ID = "SRC-INTECHOPEN-100450-KHARAJI-2021"
SOURCE_DOI = "10.5772/intechopen.100450"
SOURCE_LOCATION = "Section_4.4_Shell_diameter_Equation_58"
HEAT_TRANSFER_SURFACE = "OUTER_TUBE_SURFACE"
VALUE_AUTHORITY_REPLAY_MODEL = "REPLAY_EXACT_ACCEPTED_TASK032_REQUEST"
FRACTIONAL_POWER_ALGORITHM = "DECIMAL_LN_EXP_RATIONAL_EXPONENT_V1"

AUTHORITY_PROJECTION = (
    ENGINEERING_AUTHORITY_ID,
    SOURCE_ID,
    SOURCE_DOI,
    SOURCE_LOCATION,
    HEAT_TRANSFER_SURFACE,
    VALUE_AUTHORITY_REPLAY_MODEL,
    FRACTIONAL_POWER_ALGORITHM,
    "2e3 < Re_s < 1e6",
    "WALL_PROPERTY_REQUIRED=false",
)
ENGINEERING_AUTHORITY_HASH = sha256_hex(list(AUTHORITY_PROJECTION))


def recompute_engineering_authority_hash() -> str:
    return sha256_hex(list(AUTHORITY_PROJECTION))


__all__ = [
    "AUTHORITY_PROJECTION",
    "ENGINEERING_AUTHORITY_HASH",
    "ENGINEERING_AUTHORITY_ID",
    "ENGINEERING_SOURCE_AUTHORITY_RECORD_ID",
    "FRACTIONAL_POWER_ALGORITHM",
    "HEAT_TRANSFER_SURFACE",
    "SOURCE_DOI",
    "SOURCE_ID",
    "SOURCE_LOCATION",
    "VALUE_AUTHORITY_REPLAY_MODEL",
    "recompute_engineering_authority_hash",
]
