"""Closed failure and warning vocabulary for TASK-167.

TASK-167 is a preliminary screen.  The vocabulary deliberately contains no
standard-specific velocity or erosion limit: those limits belong to an
approved rule pack and are never inferred from a generic diagnostic.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass


class FailureStage(enum.StrEnum):
    RAW_BOUNDARY = "RAW_BOUNDARY"
    TYPED_VALIDATION = "TYPED_VALIDATION"
    UPSTREAM_REPLAY = "UPSTREAM_REPLAY"
    RULE_PACK = "RULE_PACK"
    SCREENING = "SCREENING"
    PROVENANCE = "PROVENANCE"
    IDENTITY = "IDENTITY"


class BlockerCode(enum.StrEnum):
    RAW_BOUNDARY_INVALID = "RAW_BOUNDARY_INVALID"
    RAW_UNICODE_ENCODING_FAILURE = "RAW_UNICODE_ENCODING_FAILURE"
    RAW_DEPTH_LIMIT_EXCEEDED = "RAW_DEPTH_LIMIT_EXCEEDED"
    RAW_NODE_LIMIT_EXCEEDED = "RAW_NODE_LIMIT_EXCEEDED"
    RAW_SCALAR_BYTE_LIMIT_EXCEEDED = "RAW_SCALAR_BYTE_LIMIT_EXCEEDED"
    UNSUPPORTED_RAW_VALUE = "UNSUPPORTED_RAW_VALUE"
    INVALID_REQUEST_SCHEMA = "INVALID_REQUEST_SCHEMA"
    SOURCE_DEFINITION_MISMATCH = "SOURCE_DEFINITION_MISMATCH"
    INVALID_TASK020_CONFIGURATION = "INVALID_TASK020_CONFIGURATION"
    TASK020_AUTHORITY_INVALID = "TASK020_AUTHORITY_INVALID"
    TASK166_AUTHORITY_INVALID = "TASK166_AUTHORITY_INVALID"
    TASK166_IDENTITY_REPLAY_FAILED = "TASK166_IDENTITY_REPLAY_FAILED"
    TASK166_NOT_APPLICABLE = "TASK166_NOT_APPLICABLE"
    TASK166_NOT_COMPLETE = "TASK166_NOT_COMPLETE"
    TUBE_SIDE_AUTHORITY_INVALID = "TUBE_SIDE_AUTHORITY_INVALID"
    TUBE_SIDE_IDENTITY_REPLAY_FAILED = "TUBE_SIDE_IDENTITY_REPLAY_FAILED"
    TUBE_SIDE_NOT_APPLICABLE = "TUBE_SIDE_NOT_APPLICABLE"
    TUBE_SIDE_NOT_COMPLETE = "TUBE_SIDE_NOT_COMPLETE"
    UPSTREAM_CASE_BINDING_MISMATCH = "UPSTREAM_CASE_BINDING_MISMATCH"
    SCREENING_REQUIREMENTS_INVALID = "SCREENING_REQUIREMENTS_INVALID"
    SCREENING_PROPERTY_AUTHORITY_INVALID = "SCREENING_PROPERTY_AUTHORITY_INVALID"
    NOZZLE_AUTHORITY_INVALID = "NOZZLE_AUTHORITY_INVALID"
    SCREENING_SOURCE_REQUIRED = "SCREENING_SOURCE_REQUIRED"
    SCREENING_SOURCE_CONFLICT = "SCREENING_SOURCE_CONFLICT"
    RULE_PACK_REQUIRED = "RULE_PACK_REQUIRED"
    RULE_PACK_INVALID = "RULE_PACK_INVALID"
    RULE_NOT_APPROVED = "RULE_NOT_APPROVED"
    RULE_LICENSE_BLOCKED = "RULE_LICENSE_BLOCKED"
    RULE_APPLICABILITY_UNRESOLVED = "RULE_APPLICABILITY_UNRESOLVED"
    TUBE_VELOCITY_NOT_COMPUTABLE = "TUBE_VELOCITY_NOT_COMPUTABLE"
    SHELL_VELOCITY_NOT_COMPUTABLE = "SHELL_VELOCITY_NOT_COMPUTABLE"
    NOZZLE_GEOMETRY_NOT_AVAILABLE = "NOZZLE_GEOMETRY_NOT_AVAILABLE"
    EROSION_LIMIT_AUTHORITY_MISSING = "EROSION_LIMIT_AUTHORITY_MISSING"
    FOULING_REQUIREMENT_AUTHORITY_INVALID = "FOULING_REQUIREMENT_AUTHORITY_INVALID"
    CLEANABILITY_REQUIREMENT_UNSATISFIED = "CLEANABILITY_REQUIREMENT_UNSATISFIED"
    THERMAL_EXPANSION_INPUT_INCOMPLETE = "THERMAL_EXPANSION_INPUT_INCOMPLETE"
    THERMAL_EXPANSION_LIMIT_AUTHORITY_MISSING = "THERMAL_EXPANSION_LIMIT_AUTHORITY_MISSING"
    FIV_INPUT_INCOMPLETE = "FIV_INPUT_INCOMPLETE"
    FIV_SOURCE_INCOMPLETE = "FIV_SOURCE_INCOMPLETE"
    FIV_NUMERICAL_DOMAIN_INVALID = "FIV_NUMERICAL_DOMAIN_INVALID"
    NONFINITE_ENGINEERING_RESULT = "NONFINITE_ENGINEERING_RESULT"
    CANONICALIZATION_FAILED = "CANONICALIZATION_FAILED"
    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    PARTIAL_RESULT_FORBIDDEN = "PARTIAL_RESULT_FORBIDDEN"


class WarningCode(enum.StrEnum):
    GENERIC_SCREEN_NO_STANDARD_CLAIM = "GENERIC_SCREEN_NO_STANDARD_CLAIM"
    NOZZLE_VELOCITY_NOT_EVALUATED = "NOZZLE_VELOCITY_NOT_EVALUATED"
    EROSION_LIMIT_NOT_BOUND = "EROSION_LIMIT_NOT_BOUND"
    MECHANICAL_CLEANABILITY_CAUTION = "MECHANICAL_CLEANABILITY_CAUTION"
    FIXED_TUBESHEET_DIFFERENTIAL_EXPANSION_CAUTION = (
        "FIXED_TUBESHEET_DIFFERENTIAL_EXPANSION_CAUTION"
    )
    FIV_PRELIMINARY_ONLY = "FIV_PRELIMINARY_ONLY"
    FIV_LIMIT_AUTHORITY_MISSING = "FIV_LIMIT_AUTHORITY_MISSING"
    DETAILED_MECHANICAL_ANALYSIS_DEFERRED = "DETAILED_MECHANICAL_ANALYSIS_DEFERRED"
    THERMAL_EXPANSION_DIAGNOSTIC_ONLY = "THERMAL_EXPANSION_DIAGNOSTIC_ONLY"
    SCREENING_LIMIT_UNBOUND = "SCREENING_LIMIT_UNBOUND"


@dataclass(frozen=True)
class Blocker:
    code: BlockerCode
    stage: FailureStage
    field_path: str | None = None
    message: str = ""
    evidence_refs: tuple[str, ...] = ()

    def sort_key(self) -> tuple[str, str, str, tuple[str, ...]]:
        return (self.stage.value, self.code.value, self.field_path or "", self.evidence_refs)


class ScreeningFailure(ValueError):
    """Internal typed failure converted to a deterministic blocked result."""

    def __init__(self, code: BlockerCode, field_path: str, message: str = "") -> None:
        super().__init__(message or code.value)
        self.code = code
        self.field_path = field_path


__all__ = ["Blocker", "BlockerCode", "FailureStage", "ScreeningFailure", "WarningCode"]
