"""Closed TASK-166 failure vocabulary."""

from __future__ import annotations

import enum
from dataclasses import dataclass


class FailureStage(enum.StrEnum):
    RAW_BOUNDARY = "RAW_BOUNDARY"
    TYPED_VALIDATION = "TYPED_VALIDATION"
    UPSTREAM_AUTHORITY = "UPSTREAM_AUTHORITY"
    GEOMETRY = "GEOMETRY"
    HEAT_TRANSFER = "HEAT_TRANSFER"
    PRESSURE_DROP = "PRESSURE_DROP"
    APPLICABILITY = "APPLICABILITY"
    PROVENANCE = "PROVENANCE"
    IDENTITY = "IDENTITY"


class BlockerCode(enum.StrEnum):
    RAW_SCHEMA_FAILURE = "RAW_SCHEMA_FAILURE"
    RAW_UNICODE_ENCODING_FAILURE = "RAW_UNICODE_ENCODING_FAILURE"
    RAW_DEPTH_LIMIT_EXCEEDED = "RAW_DEPTH_LIMIT_EXCEEDED"
    RAW_NODE_LIMIT_EXCEEDED = "RAW_NODE_LIMIT_EXCEEDED"
    RAW_SCALAR_BYTE_LIMIT_EXCEEDED = "RAW_SCALAR_BYTE_LIMIT_EXCEEDED"
    UNSUPPORTED_RAW_VALUE = "UNSUPPORTED_RAW_VALUE"
    SOURCE_DEFINITION_MISMATCH = "SOURCE_DEFINITION_MISMATCH"
    UNSUPPORTED_TASK166_VERSION = "UNSUPPORTED_TASK166_VERSION"
    INVALID_REQUEST_SCHEMA = "INVALID_REQUEST_SCHEMA"
    UPSTREAM_AUTHORITY_INVALID = "UPSTREAM_AUTHORITY_INVALID"
    UPSTREAM_IDENTITY_REPLAY_FAILED = "UPSTREAM_IDENTITY_REPLAY_FAILED"
    UPSTREAM_CASE_BINDING_MISMATCH = "UPSTREAM_CASE_BINDING_MISMATCH"
    CONFIGURATION_UNSUPPORTED = "CONFIGURATION_UNSUPPORTED"
    SHELL_TYPE_UNSUPPORTED = "SHELL_TYPE_UNSUPPORTED"
    SHELL_PASS_COUNT_UNSUPPORTED = "SHELL_PASS_COUNT_UNSUPPORTED"
    BAFFLE_TYPE_UNSUPPORTED = "BAFFLE_TYPE_UNSUPPORTED"
    TUBE_LAYOUT_UNSUPPORTED = "TUBE_LAYOUT_UNSUPPORTED"
    PHASE_UNSUPPORTED = "PHASE_UNSUPPORTED"
    RHEOLOGY_UNSUPPORTED = "RHEOLOGY_UNSUPPORTED"
    REYNOLDS_OUT_OF_RANGE = "REYNOLDS_OUT_OF_RANGE"
    REQUIRED_PROPERTY_MISSING = "REQUIRED_PROPERTY_MISSING"
    REQUIRED_GEOMETRY_MISSING = "REQUIRED_GEOMETRY_MISSING"
    GEOMETRY_AUTHORITY_INCOMPLETE = "GEOMETRY_AUTHORITY_INCOMPLETE"
    INVALID_GEOMETRY_DOMAIN = "INVALID_GEOMETRY_DOMAIN"
    INVALID_CORRECTION_FACTOR = "INVALID_CORRECTION_FACTOR"
    INVALID_PARAMETER_ROW = "INVALID_PARAMETER_ROW"
    SOURCE_REQUIRED = "SOURCE_REQUIRED"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    NUMERICAL_OPERATION_FAILED = "NUMERICAL_OPERATION_FAILED"
    NONFINITE_ENGINEERING_RESULT = "NONFINITE_ENGINEERING_RESULT"
    INVALID_PRESSURE_DROP_DECOMPOSITION = "INVALID_PRESSURE_DROP_DECOMPOSITION"
    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    IDENTITY_REPLAY_FAILED = "IDENTITY_REPLAY_FAILED"
    INTERNAL_INVARIANT_VIOLATION = "INTERNAL_INVARIANT_VIOLATION"


@dataclass(frozen=True)
class Blocker:
    code: BlockerCode
    stage: FailureStage
    field_path: str | None = None
    message: str = ""
    evidence_refs: tuple[str, ...] = ()

    def sort_key(self) -> tuple[str, str, str, str]:
        return (
            self.stage.value,
            self.code.value,
            self.field_path or "",
            "\x00".join(self.evidence_refs),
        )


class BellDelawareFailure(ValueError):
    """Internal, safely caught calculation failure."""

    def __init__(self, code: BlockerCode, message: str) -> None:
        super().__init__(message)
        self.code = code


__all__ = ["BellDelawareFailure", "Blocker", "BlockerCode", "FailureStage"]
